### ISSUE TITLE
Recommend `async` and `defer` attributes for `embed.js` script tag?

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/wordpress-theme-hypothesis#13]
I was checking out the Factlink.com "on your site" story:
https://factlink.com/on-your-site#on-your-site-other-platforms

And noticed that their embed code includes `async` and `defer` attributes on script tags.

Both have wide browser support:
http://caniuse.com/#feat=script-defer
http://caniuse.com/#feat=script-async

Factlink also suggests putting their script tag "near the top of your document"--which is made possible by using these attributes.

I realize developers may know about them, but they're also *really* good at copy / paste, so...might be good to just include them regardless.

@hypothesis/developers thoughts?

**Comment by tilgovi** [comment]
![Make it so](http://images.simplysyndicated.com/wp-content/uploads/2014/07/make-it-so-captain.jpg).

**Comment by BigBlueHat** [comment]
Done:
https://github.com/hypothesis/wordpress-theme-hypothesis/commit/c42691e92cb82aafc5dc26924eb9c9e961c3cb92

**Comment by tilgovi** [comment]
Cool. Feel free to deploy it.
- `make zip`
- upload to wordpress

**Comment by tilgovi** [comment]
Bump the version number, too (git tags).

**Comment by BigBlueHat** [comment]
Looks like Makefile stuff go pwnd during the upgrade. @RawKStar77 may know more.

There's no `_style.css` any longer (for instance).

I did tag a release:
https://github.com/hypothesis/wordpress-theme-hypothesis/releases/tag/v2.0.1

My guess is that I could use the .zip file from GitHub, but would like to not be the one to test that. :wink: 

@RawKStar77 if you still have a demo EC2 up, mind checkin' this change and publishing?

**Comment by tilgovi** [comment]
Looks like Jake didn't follow the readme or he would have noticed this and he would have pushed a tag.

Naughty Jake!
