### ISSUE TITLE
Add Wordpress plugin to "Add to site" modal

### ISSUE THREAD

**Issue by RawKStar77** [hypothesis/wordpress-theme-hypothesis#24]
When it's ready, we should add the WordPress plugin to our add to site modal.

**Comment by BigBlueHat** [comment]
It's ready. :smile:
https://wordpress.org/plugins/hypothesis/

**Comment by RawKStar77** [comment]
Closed with https://github.com/hypothesis/wordpress-theme-hypothesis/pull/31
