### ISSUE TITLE
Add bookmarklet for Safari to homepage

### ISSUE THREAD

**Issue by RawKStar77** [hypothesis/wordpress-theme-hypothesis#30]
Previously we've had problems with the bookmarklet on Safari. If this is no longer the case we should add it to our homepage as @judell suggested in https://github.com/hypothesis/h/issues/2132

**Comment by tilgovi** [comment]
There's no browser-specific language around the bookmarklet. I think this can probably just be closed.

**Comment by RawKStar77** [comment]
Closed with https://github.com/hypothesis/wordpress-theme-hypothesis/pull/31

**Comment by judell** [comment]
There almost certainly are still problems but no different than via where we send them now, suboptimally.

-----Original Message-----
