### ISSUE TITLE
Add <title> tags

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/wordpress-theme-hypothesis#32]
Since the site design change none of our pages have `<title>` tags. Having title tags means tab names in browsers are prettier, we're easier to find in search engines, and there's something meaningful for social networks to use when people share our pages.

Thanks!

**Comment by BigBlueHat** [comment]
Hrm...theme specific way of doing this apparently:
https://github.com/hypothesis/wordpress-theme-hypothesis/blob/f7d40550c0c36dcf1546b69a27b35ae999382fb7/lib/init.php#L15-L17

**Comment by RawKStar77** [comment]
It's only supported in WordPress version 4.1+. We're running 3.8.5, so when we can find time for @tilgovi to upgrade our WordPress install this should be resolved.

**Comment by RawKStar77** [comment]
http://codex.wordpress.org/Title_Tag

**Comment by RawKStar77** [comment]
Or we could add this backwards compatibility fix:
```
<?php
if ( ! function_exists( '_wp_render_title_tag' ) ) {
	function theme_slug_render_title() {
?>
<title><?php wp_title( '|', true, 'right' ); ?></title>
<?php
	}
	add_action( 'wp_head', 'theme_slug_render_title' );
}
?>
```

**Comment by tilgovi** [comment]
I'd love to revisit some deployment stuff after next week, so let's punt until then. Thanks, @RawKStar77.

**Comment by RawKStar77** [comment]
Now that @tilgovi has upgrade our WordPress this is resolved.

**Comment by tilgovi** [comment]
\o/
